### ISSUE TITLE
Maximize button text in window causes display issues with some fonts

### ISSUE THREAD

**Issue by tamago1908** [Shivter14/Shivtanium#7] opened 2024-09-13 13:39 UTC
The character used for the maximize button in the window on Shivtanium causes display issues with some fonts (e.g., MS Gothic). Below is an image showing the actual issue.

![Ughhhh That's why I don't like font problems](https://github.com/user-attachments/assets/506f2f14-ecee-4030-8bbb-14268223e8ac)
> The relevant part is highlighted as " This ↑"

Specifically, the core issue seems to be that the character used for the maximize button, `□` (U+25A1), is **rendered as a double-width character in some fonts like MS Gothic**. In contrast, it appears as a single-width character in other fonts. For example, in the "MxPlus IBM VGA 8x16" font, it is rendered as a single-width character.

To resolve this inconsistency, it's recommended to use a different character for the maximize button. For instance, as shown in the image below, the character `◻` (U+25FB) could be used. This character is rendered as a single-width character in both MS Gothic and MxPlus IBM VGA 8x16, which should prevent the issue.

![But_It's_not_working_well_on_my_computer](https://github.com/user-attachments/assets/e69fac7a-2d29-4c8a-9245-a4ae5b21bb51)

Also,  to avoid other troublesome problems, I suggest adding a toggle option in the settings, such as "Use alternate character" to allow users to switch if desired.

**Comment by Shivter14** [comment] 2024-09-13 19:45
Hello. Thank you for submitting your error report.
It is recommended to use the `MxPlus IBM VGA 8x16`, however, I totally respect the freedom of users wanting to use a font of their preference.

The problem is, each theme defines it's control buttons by itself. Some themes might use different control buttons.

I will fix this issue by adding an option to replace these characters with alternate characters that work on non-UTF-8 fonts like `MS Gothic`.

I will close this issue thread once this issue is resolved with the implementation stated.

**Comment by Shivter14** [comment] 2024-09-15 10:44
Hello. I implemented the fix; While doing so, I found out that the character you suggested (`◻`) had the same issue, so I used lowercase O (`o`) instead, along with replacing the `×` character with a lowercase X (`x`), and the dash for minimizing with `▿` so that it doesn't look out-of-place. I might replace it with a different character though since this one still isn't perfect.
![image](https://github.com/user-attachments/assets/bd9d912c-a8f1-4e33-8a46-d412615f12a5)

**Closed by Shivter14** 2024-09-15 10:44 UTC
